version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: financedata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: financeuser
      DB_PASSWORD: financepass
      DB_NAME: financedata
      API_KEY: your_finance_api_key_here
    volumes:
      - ./app:/app
    command: node index.js

volumes:
  postgres_data:
